### ISSUE TITLE
Add a config to only travel to a moon that was not previously visited

### ISSUE THREAD

**Issue by AlanCratys** [ZigzagAwaka/RandomMoonFX#1]
There is no option to limit the repeated arrival of planets. I need a setting to prevent planets from repeatedly arriving until all planets have been visited, otherwise many planets have almost no chance of reaching in one game.

**Comment by ZigzagAwaka** [comment]
Hello
Yep that's a good idea, I will look into adding this in the next update

**Comment by ZigzagAwaka** [comment]
Added in the latest 1.2.5 update
You can set the config `Exclude previously visited = true` to exclude previously visited moons (will reset if all moons have already been visited)
